# Generated by Django 4.2.4 on 2023-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='buy_again',
            field=models.BooleanField(default=False),
        ),
    ]
