# Generated by Django 4.2.4 on 2023-09-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='buy_again',
        ),
    ]
