# Generated by Django 4.2.4 on 2023-09-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_review_buy_again'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
