# Generated by Django 4.2.4 on 2023-09-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_text_review_comment_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
